
name: Build and Release Linux

on:
  push:
    branches:
      master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          check-latest: true
          cache: true

      - name: Check Go version
        run: go version

      - name: Install golang dependencies
        run: |
          go get .

      - name: Install robotgo dependencies
        run: |
          sudo apt-get install -y libx11-dev xorg-dev libxtst-dev xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev libxkbcommon-dev
        
      - name: Install robotgo cross-compile dependencies
        run: |
          sudo apt-get install -y gcc-multilib gcc-mingw-w64 libz-mingw-w64-dev

      - name: Run unit tests
        run: |
          go test -v

      - name: Build on linux
        run: |
          GOARCH=amd64 GOOS=linux go build gorobot-build-test .
          
      - name: Cross-compile for Windows
        run: |
          GOARCH=amd64 GOOS=windows CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ go build -o gorobot-build-test.exe .

      - name: Release package
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            gorobot-build-test
            gorobot-build-test.exe
            LICENSE
